steps:
  # Step 1: Build the Docker image with a unique tag for versioning
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/eventli-repo/eventli-app:$COMMIT_SHA'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY'
      - '--build-arg'
      - 'NEXT_PUBLIC_SITE_URL=$_NEXT_PUBLIC_SITE_URL'
      - '--build-arg'
      - 'NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$_NEXT_PUBLIC_RECAPTCHA_SITE_KEY'
      - '.'

  # Step 2: Push the uniquely tagged image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/eventli-repo/eventli-app:$COMMIT_SHA'

  # Step 3: Deploy the new image revision to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'eventli-webapp' # <-- Your Cloud Run service name
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/eventli-repo/eventli-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# This section tells Cloud Build where to get the values for the --build-arg flags
substitutions:
  _NEXT_PUBLIC_SUPABASE_URL: ''
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: ''
  _NEXT_PUBLIC_SITE_URL: ''
  _NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ''